# Generated by Django 4.2.7 on 2023-11-04 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default=None, max_length=50, null=True)),
                ('mobID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('group1', models.CharField(default=None, max_length=30)),
                ('salutation', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], max_length=4)),
                ('firstname', models.CharField(default=None, max_length=40)),
                ('primaryNumber', models.CharField(default=None, max_length=20)),
                ('primaryMail', models.EmailField(default=None, max_length=80)),
                ('city', models.CharField(default=None, max_length=30)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('pincode', models.CharField(default=None, max_length=12)),
                ('image1', models.ImageField(default=None, upload_to='cv')),
                ('donotCall', models.BooleanField(default=None)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MobDb',
            },
        ),
    ]
